app:
  title: Backstage Demo
  baseUrl: https://backstage-basic.onrender.com   # Replace with your Render URL
 
organization:
  name: My Company
 
backend:
  baseUrl: https://backstage-basic.onrender.com   # Same as app.baseUrl
  listen:
    port: ${PORT}
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'https:', 'http:']
  cors:
    origin: https://backstage-basic.onrender.com
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'   # Ephemeral DB, resets on each restart
 
auth:
  providers:
    guest: {}   # No GitHub auth, simple guest login
 
catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group, Template]
  locations:
    - type: file
      target: ./examples/entities.yaml
    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]
 
techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'
 
permission:
  enabled: true
