app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: https://backstage-basic.onrender.com
 
backend:
  # Must be publicly reachable (not localhost)
  baseUrl: https://backstage-basic.onrender.com
  listen:
    port: 7007
    host: 0.0.0.0
 
  database:
    client: better-sqlite3
    # ':memory:' will reset DB each restart. Use './backstage.db' if you want file-based,
    # but Render filesystem is ephemeral so data still won’t persist between deploys.
    connection: ':memory:'
 
auth:
  providers:
    guest: {}
 
catalog:
  # Replace example data with your real catalog sources
  locations:
    - type: file
      target: ./examples/entities.yaml
 
    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]
 
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]
